# CMake generated Testfile for 
# Source directory: /workspace
# Build directory: /workspace/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[core]=] "/workspace/build-asan/ky_test_core")
set_tests_properties([=[core]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;97;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[math]=] "/workspace/build-asan/ky_test_math")
set_tests_properties([=[math]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;101;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[ecs]=] "/workspace/build-asan/ky_test_ecs")
set_tests_properties([=[ecs]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;105;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[render]=] "/workspace/build-asan/ky_test_render")
set_tests_properties([=[render]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;109;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[physics]=] "/workspace/build-asan/ky_test_physics")
set_tests_properties([=[physics]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;113;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[script]=] "/workspace/build-asan/ky_test_script")
set_tests_properties([=[script]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;117;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[pack]=] "/workspace/build-asan/ky_test_pack")
set_tests_properties([=[pack]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;121;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[2d]=] "/workspace/build-asan/ky_test_2d")
set_tests_properties([=[2d]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;125;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[hooks]=] "/workspace/build-asan/ky_test_hooks")
set_tests_properties([=[hooks]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;129;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[event]=] "/workspace/build-asan/ky_test_event")
set_tests_properties([=[event]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;133;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[anti_tamper]=] "/workspace/build-asan/ky_test_anti_tamper")
set_tests_properties([=[anti_tamper]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;137;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[input]=] "/workspace/build-asan/ky_test_input")
set_tests_properties([=[input]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;140;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[core_quality]=] "/workspace/build-asan/ky_test_core_quality")
set_tests_properties([=[core_quality]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;144;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[demo_loop]=] "/workspace/build-asan/ky_test_demo_loop")
set_tests_properties([=[demo_loop]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;149;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[resource_flow]=] "/workspace/build-asan/ky_test_resource_flow")
set_tests_properties([=[resource_flow]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;153;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[kyx_bindings]=] "/workspace/build-asan/ky_test_kyx_bindings")
set_tests_properties([=[kyx_bindings]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;157;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[kyx_gc]=] "/workspace/build-asan/ky_test_kyx_gc")
set_tests_properties([=[kyx_gc]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;161;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[editor_world]=] "/workspace/build-asan/ky_test_editor_world")
set_tests_properties([=[editor_world]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;169;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[scene_serialize]=] "/workspace/build-asan/ky_test_scene_serialize")
set_tests_properties([=[scene_serialize]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;174;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[spritesheet]=] "/workspace/build-asan/ky_test_spritesheet")
set_tests_properties([=[spritesheet]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;178;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[extreme]=] "/workspace/build-asan/ky_test_extreme")
set_tests_properties([=[extreme]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;182;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[particle]=] "/workspace/build-asan/ky_test_particle")
set_tests_properties([=[particle]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;186;ky_add_test;/workspace/CMakeLists.txt;0;")
add_test([=[audio]=] "/workspace/build-asan/ky_test_audio")
set_tests_properties([=[audio]=] PROPERTIES  ENVIRONMENT "LSAN_OPTIONS=suppressions=/workspace/lsan.supp" _BACKTRACE_TRIPLES "/workspace/CMakeLists.txt;89;add_test;/workspace/CMakeLists.txt;190;ky_add_test;/workspace/CMakeLists.txt;0;")
