option(KYR_BUILD_TESTS "Build unit tests" ON)
option(KYR_BUILD_DEMOS "Build demo games" ON)
option(KYR_BUILD_EDITOR "Build ImGui editor" OFF)
option(KYR_BUILD_PYTHON "Build Python bindings" OFF)
option(KYR_RENDERER_GL "Enable OpenGL backend" ON)
option(KYR_RENDERER_VULKAN "Enable Vulkan backend" OFF)
option(KYR_ENABLE_SANITIZERS "Enable ASan/UBSan in debug" OFF)
